name: Build Docs and Deploy
on:
  push:
    paths: ["src/components/**"]
jobs:
  build-docs-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout...
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: Install dependencies...
        run: yarn install
      - name: Build stories...
        run: yarn build:storybook
      - name: Deploy...
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: main
          FOLDER: docs
          CLEAN: true
